### PR TITLE
Commit

### PR DESCRIPTION
**Pull request by VAbrishamii**

### CODE REVIEW

**Comment by VAbrishamii** [comment]
- name: 'about Us' 
    label: 'About Us' 
    folder: 'about_us' 
    create: false 
    fields: [] 

  - name: 'about MMF' 
    label: 'about MMF'
    folder: 'about_us/about_mmf'
    create: true 
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: 'Our history'
    label: 'Our history' 
    folder: 'about_us/our_history'
    create: true 
    fields: 
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: 'The employees' 
    label: 'The employees' 
    folder: 'about_us/the_employees' 
    create: true 
    fields: 
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown', hint: 'Employee bio.' }

  - name: 'Funds'
    label: 'Where do we get funds from?' 
    folder: 'about_us/funds' 
    create: true 
    fields: 
      - { label: 'Source', name: 'source', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown', hint: 'Description of funding source.' }

**Comment by AnnaAaBrekke** [comment]
Nice! Is this added or replacing the previous one? :) And is it under the collection or pages?

**Comment by VAbrishamii** [comment]
I this under the collection. and added to previous one

**Comment by AnnaAaBrekke** [comment]
It is okay by me if you want to try to merge into the main to check if it works on the website/page :)

**Pull request merged**
